# Project 4: Systems of Linear Equation Solving

This week we will go over Gauss-Jordan and the algorithm to solve it.

# Rows function

Firstly, we need to write methods for operation on rows needed for Jordan-Gauss method, which includes adding, swapping, and multiplying.

Please note that I will make a copy of the matrix list and modify parts needed to be changed instead of appending to a totally new list within the function.

In [32]:
import math
import numpy as np

matrix = np.array([[3,2,3,1], [6,-4,1,2], [9,-2,4,3]])


#SWAP ROWS

def swap(matrx, r1, r2):
    temp = matrx.copy()
    temp[[r1, r2]] = temp[[r2, r1]]
    return np.array(temp)

swap(matrix, 1, 2)    


array([[ 3,  2,  3,  1],
       [ 9, -2,  4,  3],
       [ 6, -4,  1,  2]])

In [33]:
#ADD


def addRow(matrx, row, toAdd, multiplier):
    temp = matrx.copy()
    for i in range(len(matrx[row, :])):
        temp[row, i] = temp[row, i] + multiplier*temp[toAdd, i]
    return np.array(temp)

addRow(matrix, 1, 2, 5)


array([[  3,   2,   3,   1],
       [ 51, -14,  21,  17],
       [  9,  -2,   4,   3]])

In [34]:
def toLeading1(matrx, row, col):
    temp = matrx.copy()
    temp = np.array(temp, float)
    temp[row, :] = temp[row, :]/temp[row, col]
    return np.array(temp)

toLeading1(matrix, 0, 0)
    

array([[ 1.        ,  0.66666667,  1.        ,  0.33333333],
       [ 6.        , -4.        ,  1.        ,  2.        ],
       [ 9.        , -2.        ,  4.        ,  3.        ]])

Next part is to perform these functions on  at least a system of 3 functions and three unknown, which I assume to be the same.

In [35]:
A = np.array([[2, 3, -1], [1, -1, 1], [3, 4, -2]])

We already have leading zero on row 1, so we can go ahead and skip that step.

In [36]:
A = addRow(A, 1, 0, -1)
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 3,  4, -2]])

In [37]:
A = addRow(A, 2, 0, 1)
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 5,  7, -3]])

In [38]:
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 5,  7, -3]])

In [39]:
A = toLeading1(A, 1, 1)
A

array([[ 2.  ,  3.  , -1.  ],
       [ 0.25,  1.  , -0.5 ],
       [ 5.  ,  7.  , -3.  ]])

In [40]:
A = addRow(A, 0, 1, -5)
A

array([[ 0.75, -2.  ,  1.5 ],
       [ 0.25,  1.  , -0.5 ],
       [ 5.  ,  7.  , -3.  ]])

In [41]:
addRow(A, 2, 1, -2)

array([[ 0.75, -2.  ,  1.5 ],
       [ 0.25,  1.  , -0.5 ],
       [ 4.5 ,  5.  , -2.  ]])

In the next part of the question we create an algorithm for solving systems of equations following the Gauss-Jordan elimination method

In [42]:
def gauss_jordan(A, b):
    matrix = np.concatenate((A, b.reshape(-1,1)), axis=1)
    rows, cols = matrix.shape
    for j in range(cols-1):
        if not np.any(matrix[j:, j]):
            raise ValueError("System of equations has infinitely many solutions or no solution")
        row_max = np.argmax(np.abs(matrix[j:, j])) + j
        matrix[[j, row_max]] = matrix[[row_max, j]]
        matrix[j, :] = matrix[j, :] / matrix[j, j]
        for i in range(rows):
            if i != j:
                matrix[i, :] = matrix[i, :] - matrix[i, j]*matrix[j, :]
    x = matrix[:, -1]
    return x

# Example system of equations:
# 2x + 3y - z = 1
# x - y + z = 3
# 3x + 4y - 2z = -1

# Converting the equations into matrix form
A = np.array([[2, 3, -1], [1, -1, 1], [3, 4, -2]])
B = np.array([1, 3, -1])

# Solving the above system using Gauss-Jordan elimination
x = gauss_jordan(A, B)
print(x)


[ 1 -1 -2]
